### ISSUE TITLE
Hey! Guys, Your webSite IS SQL VuLn

### ISSUE THREAD

**Issue by jas502n** [leonwxqian/n0o-vuln-archive#1]
http://n0o.com/index.php?category=1%20and%201=1
http://n0o.com/index.php?category=1%20and%201=2

fix SQL!

**Comment by leonwxqian** [comment]
Yeah that's it, thank you very much!  I have noticed this one and this is fixed, I will check other places too :)

非常感谢，刚刚在线上调试网站，修改了以后没想到这么快就被抓到了，哈哈。这个程序是从一个simple blog拿来的，有些地方实现不安全，您报告的我已经修复了，我也正在排查其他地方。再次感谢。

**Comment by leonwxqian** [comment]
Close issue since problem is solved. Cheers :)!

问题已解决，关闭issue。感谢白帽子！
